CREDENTIALS = (
    ("None", "None"),
    ("MD", "MD"),
    ("DO", "DO"),
    ("MBBS", "MBBS"),
    ("MBBCh", "MBBCh"),
    ("PhD", "PhD"),
    ("DNP", "DNP"),
    ("NP", "NP"),
    ("PA", "PA"),
    ("CNP", "CNP"),
    ("CNNP", "CNNP"),
    ("PA", "PA"),
    ("CNS", "CNS"),
    ("CNM", "CNM"),
)
